// Auto-generated by pivota init-dev-server. Extends user's next.config to permit
// Daytona preview origin embedding in dev. Phase 39 will refine this; for now
// the overlay is a best-effort seed that only takes effect for Next versions
// that expose a dynamic config-merge hook (see Notes in catalog entry).
module.exports = (phase, { defaultConfig }) => {
  let user = {};
  try { user = require('../next.config.js'); }
  catch { try { user = require('../next.config.mjs').default || {}; } catch {} }
  if (typeof user === 'function') user = user(phase, { defaultConfig });
  return {
    ...user,
    allowedDevOrigins: [
      ...(user.allowedDevOrigins || []),
      '*.preview.daytona.io',
      '*.daytona.work',
    ],
  };
};
