#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: react-next
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — RESEARCH.md
#     Pitfall 6 (sentinel survives reboots but install output dirs may not on
#     fresh tmpfs; never skip on a clean directory).
#   - Retry exits with INNER command's last exit code (not a fixed 1) so callers
#     can disambiguate failures from the wrapper.
#   - run_install has an npm ERESOLVE fallback (--legacy-peer-deps) + a FATAL
#     marker (D-12.1) — a scaffold with a lagging peer range must not silently
#     leave node_modules empty and hang the preview on "Waiting to bind".

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
# Researcher resolved log destination: /tmp/pivota-dev.log (always writable,
# matches existing convention). SSE chat panel sees output live AND a file
# exists for scrollback / replay.
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: react-next)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
# NOTE: env vars do NOT cover every stack. Vite / webpack-dev-server / Next.js
# allowedHosts require CLI flags or config-file overlays — those live in
# EXEC_CMD or PRE_EXEC_SNIPPET below, not here.
export HOSTNAME=0.0.0.0
export HOST=0.0.0.0
# HOSTNAME is honored by Next.js for the dev server bind address since v13.
# CITED: nextjs.org/docs/app/api-reference/config/next-config-js — output.
#
# For allowedDevOrigins (required for sandbox preview iframe embedding on
# Next 14.x+), there is NO env var; it is a next.config.* field only.
# See the pre-exec snippet below — we write a small overlay file as a
# best-effort seed. Read the `## Notes` section for limitations.
#
# HOST=0.0.0.0 is also exported for the rare downstream tool / script that
# reads $HOST for its own host-binding decisions (Next itself ignores it).

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
# Seed .env from .env.example for first boot, but NEVER let an .env.example
# placeholder shadow a variable the platform already injected into the sandbox
# environment. The motivating bug: .env.example shipped a dead
# `DATABASE_URL=postgresql://user:pass@localhost/...` that overrode the injected
# sidecar DATABASE_URL, so Prisma `db push`/`$connect()` failed. Any KEY already
# set in the environment (DATABASE_URL, POSTGRES_*/MYSQL_*, REDIS_URL, PIVOTA_*,
# plus PORT/NODE_ENV from the preamble above) is dropped from the copy so the
# injected value wins. See references/runtime-environment.md §3.
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"   # left-trim for the test only
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue            # keep comments / blanks / non-assignments
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === Optional pre-exec snippet (JDK install, rustup, golang one-shot setup) ===
# Catalog entries with PRE_EXEC_SNIPPET inject heavyweight one-time installs
# here. Empty string when not needed.

# Only patch if user's next.config doesn't already include allowedDevOrigins.
for CFG in next.config.mjs next.config.js next.config.ts; do
  if [[ -f "$CFG" ]]; then
    if ! grep -q "allowedDevOrigins" "$CFG" 2>/dev/null; then
      mkdir -p .pivota
      cat > .pivota/next.config.pivota.cjs <<'EOF'
// Auto-generated by pivota init-dev-server. Extends user's next.config to permit
// Daytona preview origin embedding in dev. Phase 39 will refine this; for now
// the overlay is a best-effort seed that only takes effect for Next versions
// that expose a dynamic config-merge hook (see Notes in catalog entry).
module.exports = (phase, { defaultConfig }) => {
  let user = {};
  try { user = require('../next.config.js'); }
  catch { try { user = require('../next.config.mjs').default || {}; } catch {} }
  if (typeof user === 'function') user = user(phase, { defaultConfig });
  return {
    ...user,
    allowedDevOrigins: [
      ...(user.allowedDevOrigins || []),
      '*.preview.daytona.io',
      '*.daytona.work',
    ],
  };
};
EOF
      echo "[pivota] wrote .pivota/next.config.pivota.cjs (allowedDevOrigins overlay)"
    fi
    break
  fi
done

# Best-effort schema migration on platform-provided-DB backends (K8s / Local):
# when the platform injects a database (PIVOTA_DB_MODE / DATABASE_URL set) and
# the app declares a `migrate` script, run it BEFORE the dev server so the
# schema exists on first request — even if the app's `dev` script didn't chain
# `npm run migrate && …`. Migrations are expected to be idempotent
# (CREATE TABLE IF NOT EXISTS …), so a repeat when `dev` also runs migrate is
# safe. No-op on Daytona (no injected DATABASE_URL → compose/DinD owns the DB).
if [ -n "${PIVOTA_DB_MODE:-}" ] || [ -n "${DATABASE_URL:-}" ]; then
  if node -e "process.exit(require('./package.json').scripts?.migrate?0:1)" 2>/dev/null; then
    echo "[pivota] platform DB detected — running 'npm run migrate' (best-effort) before dev server"
    npm run migrate || echo "[pivota] migrate non-zero (continuing; dev script may re-run it)"
  fi
  # Also try db:migrate if present (this project uses drizzle's db:migrate convention)
  if node -e "process.exit(require('./package.json').scripts?.['db:migrate']?0:1)" 2>/dev/null; then
    echo "[pivota] platform DB detected — running 'npm run db:migrate' (best-effort) before dev server"
    npm run db:migrate || echo "[pivota] db:migrate non-zero (continuing; dev script may re-run it)"
  fi
fi

# === D-12: idempotent install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="package-lock.json"
INSTALL_PRESENCE_CHECK="node_modules"
INSTALL_CMD='npm ci || npm install'   # single-quoted: catalog must escape internal quotes correctly

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  local rc=0
  bash -c "$INSTALL_CMD" || rc=$?   # capture directly; `if …; then` would reset $? to 0 on the no-else path
  if (( rc == 0 )); then
    return 0
  fi
  # D-12.1: npm peer-dependency (ERESOLVE) fallback + loud failure.
  # A fresh scaffold can pin a transitive lib whose peer range lags the
  # project's react/next major (observed: react-leaflet@4 wants react@18 under
  # a react@19 project). npm 7+ aborts `npm ci`/`npm install` with ERESOLVE and
  # writes NO node_modules — so EXEC_CMD below never binds a port and the
  # preview panel hangs on "Waiting for dev server to bind…" with no surfaced
  # error. Retry once with --legacy-peer-deps so boot can proceed, but log
  # LOUDLY: a force-resolved peer range can install a runtime-incompatible tree
  # (the offending component may crash when rendered — surface it at UAT).
  if [[ "$INSTALL_CMD" == *"npm "* ]]; then
    echo "[pivota] WARN install failed (exit=$rc) — retrying with --legacy-peer-deps (peer conflict force-resolved; runtime incompatibility possible)"
    local rc2=0
    npm install --legacy-peer-deps || rc2=$?
    if (( rc2 == 0 )); then
      echo "[pivota] WARN install succeeded via --legacy-peer-deps fallback — a dependency's peer range is unsatisfied; fix package.json (this is a real bug, not just a warning)"
      return 0
    fi
    rc=$rc2
  fi
  # Emit a greppable marker so the platform surfaces "install failed" instead of
  # letting the dev server silently never bind. `set -e` still aborts the script.
  echo "[pivota] FATAL install failed (exit=$rc) — dev server cannot start; resolve the dependency conflict in the manifest" >&2
  return "$rc"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")

  # RESEARCH.md Pitfall 6: lockfile-unchanged is necessary but not sufficient —
  # the install-output directory must also exist (sentinel survives but
  # node_modules / .venv / target might not on a fresh sandbox tmpfs).
  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi

  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  # No lockfile to compare; honor any sentinel mismatch by running install once per sandbox.
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
# Final-attempt exit code propagates the INNER command's exit code, not a
# fixed 1, so the caller (platform / Daytona) can distinguish "wrapper bug"
# from "user command failed with N".
EXEC_CMD='npm run dev -- --hostname 0.0.0.0 --port 3000'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
