#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: react-next
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — RESEARCH.md
#     Pitfall 6 (sentinel survives reboots but install output dirs may not on
#     fresh tmpfs; never skip on a clean directory).
#   - Retry exits with INNER command's last exit code (not a fixed 1) so callers
#     can disambiguate failures from the wrapper.
#   - run_install has an npm ERESOLVE fallback (--legacy-peer-deps) + a FATAL
#     marker (D-12.1) — a scaffold with a lagging peer range must not silently
#     leave node_modules empty and hang the preview on "Waiting to bind".

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Single-instance guard ===
# Multiple platform paths can invoke the wrapper concurrently (sandbox setup,
# preview open, verify pre-flight) — observed as two `docker compose up --build`
# trees racing in one sandbox. Second invocation exits 0 quietly: the first
# boot is authoritative and callers poll the port, not this process.
exec 200>/tmp/pivota-dev.lock
if ! flock -n 200; then
  echo "[pivota] start-dev.sh already running (lock held) — exiting; poll the ready port instead" >&2
  exit 0
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
# Researcher resolved log destination: /tmp/pivota-dev.log (always writable,
# matches existing convention). SSE chat panel sees output live AND a file
# exists for scrollback / replay.
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: react-next)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
# NOTE: env vars do NOT cover every stack. Vite / webpack-dev-server / Next.js
# allowedHosts require CLI flags or config-file overlays — those live in
# EXEC_CMD or PRE_EXEC_SNIPPET below, not here.
export HOSTNAME=0.0.0.0
export HOST=0.0.0.0
# HOSTNAME is honored by Next.js for the dev server bind address since v13.
# CITED: nextjs.org/docs/app/api-reference/config/next-config-js — output.
#
# For allowedDevOrigins (required for sandbox preview iframe embedding on
# Next 14.x+), there is NO env var; it is a next.config.* field only.
# See the pre-exec snippet below — we write a small overlay file as a
# best-effort seed. Read the `## Notes` section for limitations.
#
# HOST=0.0.0.0 is also exported for the rare downstream tool / script that
# reads $HOST for its own host-binding decisions (Next itself ignores it).

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
# Seed .env from .env.example for first boot, but NEVER let an .env.example
# placeholder shadow a variable the platform already injected into the sandbox
# environment. The motivating bug: .env.example shipped a dead
# `DATABASE_URL=postgresql://user:pass@localhost/...` that overrode the injected
# sidecar DATABASE_URL, so Prisma `db push`/`$connect()` failed. Any KEY already
# set in the environment (DATABASE_URL, POSTGRES_*/MYSQL_*, REDIS_URL, PIVOTA_*,
# plus PORT/NODE_ENV from the preamble above) is dropped from the copy so the
# injected value wins. See references/runtime-environment.md §3.
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"   # left-trim for the test only
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue            # keep comments / blanks / non-assignments
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    # D-11.5: sanitize the copied assignment. Documented .env.example files
    # column-align inline `# comments` after values, and docker compose's .env
    # parser passes those through as part of the value (motivating bug:
    # `LDAP_URL=   # LDAP server URL, e.g. ldap://…` made a Spring app treat
    # LDAP as enabled and crash-loop on boot, so the compose frontend behind a
    # `service_healthy` dependency never started). Strip them from unquoted
    # values only — a `#` inside quotes is part of the value.
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    # Replace CHANGE_ME placeholder secrets with generated values. Placeholders
    # are landmines at runtime, not just cosmetics: jjwt hard-rejects HMAC keys
    # under 256 bits, so `JWT_SECRET=CHANGE_ME_BASE64_256BIT_SECRET` (240 bits)
    # 500s every login. Same generated value is seen by every compose service
    # reading this .env, so cross-service credentials stay consistent.
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === Optional pre-exec snippet (JDK install, rustup, golang one-shot setup) ===
# Catalog entries with PRE_EXEC_SNIPPET inject heavyweight one-time installs
# here. Empty string when not needed.

# -- allowedDevOrigins overlay (react-next catalog entry) --
# Only patch if user's next.config doesn't already include allowedDevOrigins.
for CFG in next.config.mjs next.config.js next.config.ts; do
  if [[ -f "$CFG" ]]; then
    if ! grep -q "allowedDevOrigins" "$CFG" 2>/dev/null; then
      mkdir -p .pivota
      cat > .pivota/next.config.pivota.cjs <<'EOF'
// Auto-generated by pivota init-dev-server. Extends user's next.config to permit
// Daytona preview origin embedding in dev. Phase 39 will refine this; for now
// the overlay is a best-effort seed that only takes effect for Next versions
// that expose a dynamic config-merge hook (see Notes in catalog entry).
module.exports = (phase, { defaultConfig }) => {
  let user = {};
  try { user = require('../next.config.js'); }
  catch { try { user = require('../next.config.mjs').default || {}; } catch {} }
  if (typeof user === 'function') user = user(phase, { defaultConfig });
  return {
    ...user,
    allowedDevOrigins: [
      ...(user.allowedDevOrigins || []),
      '*.preview.daytona.io',
      '*.daytona.work',
    ],
  };
};
EOF
      echo "[pivota] wrote .pivota/next.config.pivota.cjs (allowedDevOrigins overlay)"
    fi
    break
  fi
done

# NB: no migrate hook here. This slot runs BEFORE `npm ci` (no node_modules —
# a node/prisma migrator would fail with `prisma: not found`; that exact
# swallowed failure once shipped an empty-DB app). A DB-backed Next.js app
# provisions its DB via its own docker-compose.yml, where migrate → seed →
# serve run inside the app service command AFTER the image's install step —
# see references/runtime-environment.md §3.

# -- Start compose db service (project-specific: provides postgres:16 on :5432) --
# The project's docker-compose.yml app service builds a production image
# (`next build` → `node server.js`). We run `next dev` natively instead
# (the gitignored .next/standalone is absent after a fresh clone, so
# `node server.js` would fail). We only need the `db` service for DATABASE_URL.
if docker info >/dev/null 2>&1; then
  echo "[pivota] starting compose db service (postgres:16)"
  docker compose up -d db 2>&1 || {
    echo "[pivota] WARN: docker compose up -d db failed — will proceed; DB-backed routes may fail" >&2
  }
  # Wait for the db healthcheck to pass (up to 60s)
  echo "[pivota] waiting for db to become healthy..."
  DB_READY=0
  for i in $(seq 1 12); do
    if (exec 3<>"/dev/tcp/127.0.0.1/5432") 2>/dev/null; then
      exec 3>&-
      DB_READY=1
      echo "[pivota] db port 5432 is reachable"
      break
    fi
    echo "[pivota] waiting for db... attempt $i/12"
    sleep 5
  done
  if [[ "$DB_READY" == "0" ]]; then
    echo "[pivota] WARN: db did not become reachable within 60s — migrations may fail" >&2
  fi
else
  echo "[pivota] WARN: docker not available — cannot start compose db service; DB-backed routes will fail" >&2
fi

# === D-12: idempotent install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="package-lock.json"
INSTALL_PRESENCE_CHECK="node_modules"
INSTALL_CMD='npm ci || npm install'   # single-quoted: catalog must escape internal quotes correctly

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  local rc=0
  bash -c "$INSTALL_CMD" || rc=$?   # capture directly; `if …; then` would reset $? to 0 on the no-else path
  if (( rc == 0 )); then
    return 0
  fi
  # D-12.1: npm peer-dependency (ERESOLVE) fallback + loud failure.
  # A fresh scaffold can pin a transitive lib whose peer range lags the
  # project's react/next major (observed: react-leaflet@4 wants react@18 under
  # a react@19 project). npm 7+ aborts `npm ci`/`npm install` with ERESOLVE and
  # writes NO node_modules — so EXEC_CMD below never binds a port and the
  # preview panel hangs on "Waiting for dev server to bind…" with no surfaced
  # error. Retry once with --legacy-peer-deps so boot can proceed, but log
  # LOUDLY: a force-resolved peer range can install a runtime-incompatible tree
  # (the offending component may crash when rendered — surface it at UAT).
  if [[ "$INSTALL_CMD" == *"npm "* ]]; then
    echo "[pivota] WARN install failed (exit=$rc) — retrying with --legacy-peer-deps (peer conflict force-resolved; runtime incompatibility possible)"
    local rc2=0
    npm install --legacy-peer-deps || rc2=$?
    if (( rc2 == 0 )); then
      echo "[pivota] WARN install succeeded via --legacy-peer-deps fallback — a dependency's peer range is unsatisfied; fix package.json (this is a real bug, not just a warning)"
      return 0
    fi
    rc=$rc2
  fi
  # Emit a greppable marker so the platform surfaces "install failed" instead of
  # letting the dev server silently never bind. `set -e` still aborts the script.
  echo "[pivota] FATAL install failed (exit=$rc) — dev server cannot start; resolve the dependency conflict in the manifest" >&2
  return "$rc"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")

  # RESEARCH.md Pitfall 6: lockfile-unchanged is necessary but not sufficient —
  # the install-output directory must also exist (sentinel survives but
  # node_modules / .venv / target might not on a fresh sandbox tmpfs).
  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi

  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  # No lockfile to compare; honor any sentinel mismatch by running install once per sandbox.
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === Post-install: run DB migrations then seed (AFTER npm ci — tsx/drizzle-kit require node_modules) ===
# Uses tsx and drizzle-kit from devDependencies. Non-fatal: a transient DB
# hiccup at boot does not strand the dev server.
echo "[pivota] running DB migrations (npm run db:migrate)"
npm run db:migrate 2>&1 || {
  EXIT_M=$?
  echo "[pivota] WARN: db:migrate exited $EXIT_M — app may boot onto an empty/stale schema; check DB connectivity and rerun if needed" >&2
}

echo "[pivota] running DB seed (npm run db:seed)"
npm run db:seed 2>&1 || {
  EXIT_S=$?
  echo "[pivota] WARN: db:seed exited $EXIT_S — continuing; seed data may be absent" >&2
}

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
# Final-attempt exit code propagates the INNER command's exit code, not a
# fixed 1, so the caller (platform / Daytona) can distinguish "wrapper bug"
# from "user command failed with N".
EXEC_CMD='npx next dev -H 0.0.0.0 -p 3002'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
