#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent-synthesized
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Agent fallback: multi-match (compose + react-next) — project has both
#     docker-compose.yml (with db+app services) and next.config.ts. The compose
#     file is the canonical infrastructure spec: db healthcheck → migrate → seed →
#     serve. `docker compose up --build` is the correct exec so both DB provisioning
#     and the Next.js app start together.
#   - EXEC_CMD is `docker compose up --build` (not `npm run dev`) because:
#     (a) the DB (postgres) is declared in docker-compose.yml and must be started;
#     (b) the compose app command already runs drizzle migrate → seed → serve;
#     (c) running native `next dev` would skip DB provisioning.
#   - No lockfile sentinel / INSTALL_CMD: compose manages its own image layer cache
#     (`--build` rebuilds only changed layers); no npm install step needed in wrapper.
#   - Ready ports: 3000 (the app service publishes 3000:3000 per compose file).

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Single-instance guard ===
# Multiple platform paths can invoke the wrapper concurrently (sandbox setup,
# preview open, verify pre-flight) — observed as two `docker compose up --build`
# trees racing in one sandbox. Second invocation exits 0 quietly: the first
# boot is authoritative and callers poll the port, not this process.
exec 200>/tmp/pivota-dev.lock
if ! flock -n 200; then
  echo "[pivota] start-dev.sh already running (lock held) — exiting; poll the ready port instead" >&2
  exit 0
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
# Researcher resolved log destination: /tmp/pivota-dev.log (always writable,
# matches existing convention). SSE chat panel sees output live AND a file
# exists for scrollback / replay.
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent-synthesized)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
# Compose services control their own bind addresses via the `ports:` block in
# the compose file — there is no env-var lever the wrapper can pull to force
# 0.0.0.0 binding for child containers. The compose file already declares
# ports: ["3000:3000"] which binds on the sandbox's all-interfaces address.
# The app service sets HOSTNAME=0.0.0.0 in its environment block.
# No wrapper-level env preamble needed for compose.

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
# Seed .env from .env.example for first boot, but NEVER let an .env.example
# placeholder shadow a variable the platform already injected into the sandbox
# environment. The motivating bug: .env.example shipped a dead
# `DATABASE_URL=postgresql://user:pass@localhost/...` that overrode the injected
# sidecar DATABASE_URL, so Prisma `db push`/`$connect()` failed. Any KEY already
# set in the environment (DATABASE_URL, POSTGRES_*/MYSQL_*, REDIS_URL, PIVOTA_*,
# plus PORT/NODE_ENV from the preamble above) is dropped from the copy so the
# injected value wins. See references/runtime-environment.md §3.
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"   # left-trim for the test only
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue            # keep comments / blanks / non-assignments
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    # D-11.5: sanitize the copied assignment. Documented .env.example files
    # column-align inline `# comments` after values, and docker compose's .env
    # parser passes those through as part of the value. Strip them from unquoted
    # values only — a `#` inside quotes is part of the value.
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    # Replace CHANGE_ME placeholder secrets with generated values. Placeholders
    # are landmines at runtime: jjwt hard-rejects HMAC keys under 256 bits.
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === No pre-exec snippet needed for compose ===
# The compose file owns its own build step (Dockerfile) and DB provisioning.
# No JDK/rustup/golang one-shot installs required.

# === No lockfile sentinel / install step for compose ===
# `docker compose up --build` manages its own image layer cache.
# No LOCK_FILE or INSTALL_CMD substitution needed.

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
# Compose is a single foreground process from the wrapper's perspective
# (multi-process-template.md §6 documents this fast path explicitly).
# The single-process retry loop applies.
EXEC_CMD='docker compose up --build'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
